name: Train-Pipeline

on:
  push:
  pull_request:
    branches:
    - main
    - layers
    - branch_01
  workflow_dispatch:
  # Allows external webhook trigger
  repository_dispatch:
    types:
      - webhook
jobs:
  test_train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: Set up Python 3.10.18
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.18

      - name: Install dependencies
        # tensorflow - o pacote n達o estava no requirements.txt, vers達o local 2.18.0
        run: |
          python -m pip install --upgrade pip
          pip install tensorflow 
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Test files
        run: |
          pytest my_train_test.py

  train_pipeline:
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v1
            with:
              fetch-depth: 0

          - name: Set up Python 3.10.18
            uses: actions/setup-python@v1
            with:
                python-version: 3.10.18

          - name: Install dependencies
            # tensorflow - o pacote n達o estava no requirements.txt, vers達o local 2.18.0
            run: |
                python -m pip install --upgrade pip
                pip install tensorflow 
                if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

          - name: Train Model
            run: |
              python train.py
